#!/usr/bin/env ruby

def string_in_files(files, string)
  files.each do |file|
    nocommit = %x{ ag "#{string}" "#{file}" }
    unless nocommit.empty?
      puts "Error: You have #{string} in your code."
      puts "In file [#{file}]"
      puts nocommit
      exit 1
    end
  end
end

git_root = %x{ git rev-parse --show-toplevel }.gsub("\n", "")
staged_files = %x{ git diff --name-only --staged }.split(' ')
staged_files = staged_files.map { |file| File.join(git_root, file) }
forbidden_words = ["NOCOMMIT", "puts", "console.log"]
forbidden_words.each { |forbidden_word| string_in_files(staged_files, forbidden_word) }
