#!/usr/bin/env ruby

UNCONCERNED_BRANCHES = ["dev", "master"]
current_branch=%x{ git rev-parse --abbrev-ref HEAD }.strip
commit_file_msg = ARGV[0].strip
commit_msg = %x{ cat #{commit_file_msg} }.strip

def branch_unconcerned?(branch)
  UNCONCERNED_BRANCHES.include?(branch)
end

return if branch_unconcerned?(current_branch)

if commit_msg.start_with?("fixup")
  %x{ echo "fixup! #{current_branch} ${commit_msg[6..-1]}" > #{commit_file_msg} }
elsif ! commit_msg.start_with?(current_branch) && ! current_branch.start_with?("HEAD")
  %x{ echo "#{current_branch} #{commit_msg}" > #{commit_file_msg} }
end
